services:
  - type: web
    name: namfonshop
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: apache2-foreground
    envVars:
      - key: HTTP_HOST
        value: render
